### PR TITLE
edited params so you can pass a custom response object (with cookies, header etc.)

### PR DESCRIPTION
**Pull request by geovanigaldemsugar**
this is my first time contributing anything open source, so  i  probably made a mistake or something just send a email or reply

### CODE REVIEW

**Comment by mimseyedi** [comment]
I am glad of your participation. But the existence of the url parameter means that the requests.Response object will be created by it in the body of the download method and prevent possible errors by the user to send a requests.Response object as an argument. I don't feel the need to take a requests.Response object as an argument from the outside. Unless I'm missing something, and if so, I'd be happy if you could give me detailed information.

**Comment by geovanigaldemsugar** [comment]
Alright, it is just that, access to some URLs requires custom cookies or headers and passing a request. Response object will fix that issue but I also understand how that can open up more room for errors. this was an issue I had and I liked the package so I thought maybe I would try and fix it.

### When trying to download a video from a restricted Url

```python
from dlbar import DownloadBar


#  some retricted url a tiktok url in this case
url = "https://v16-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/oEtOUtQeIEjRDzhD2ZmEDDaBAEnASI1fgAOF0R/?a=1988&bti=NDU3ZjAwOg%3D%3D&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C&cv=1&br=3058&bt=1529&cs=0&ds=6&ft=4fUEKMwG8Zmo0Zk8q-4jVFQjZpWrKsd.&mime_type=video_mp4&qs=0&rc=ZDZkZDhmaTdoOmY7ZjVnNUBpM2s1anA5cjZwcjMzZzczNEBhLTMyYzFgNjMxM2JeNTA2YSNzNS5nMmRrXi5gLS1kMS9zcw%3D%3D&btag=e00098000&expire=1716763169&l=202405242236252EE7B86E9554CB15C72C&ply_type=2&policy=2&signature=49bdfda002c4f9cc8f477197d427a563&tk=tt_chain_token"


DownloadBar().download( dest='video.mp4', title='Video')
```
output
 but the video isn't 512 bytes, it just defaults to downloading the html page.
 
```python
# changed file extention to html to see response
DownloadBar().download( dest='video.html', title='Video')
```
output_html


###  With `request.response` object 
 ```python
 from dlbar import DownloadBar
import requests

#  some retricted url  a tiktok url in this case
url ="https://v16-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/oEtOUtQeIEjRDzhD2ZmEDDaBAEnASI1fgAOF0R/?a=1988&bti=NDU3ZjAwOg%3D%3D&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C&cv=1&br=3058&bt=1529&cs=0&ds=6&ft=4fUEKMwG8Zmo0Zk8q-4jVFQjZpWrKsd.&mime_type=video_mp4&qs=0&rc=ZDZkZDhmaTdoOmY7ZjVnNUBpM2s1anA5cjZwcjMzZzczNEBhLTMyYzFgNjMxM2JeNTA2YSNzNS5nMmRrXi5gLS1kMS9zcw%3D%3D&btag=e00098000&expire=1716763169&l=202405242236252EE7B86E9554CB15C72C&ply_type=2&policy=2&signature=49bdfda002c4f9cc8f477197d427a563&tk=tt_chain_token"

# changed file extention to html to see response
cookies = {
    "passport_csrf_token": "1c61fac01d7e3e52871b941f580dff76",
    "passport_csrf_token_default": "1c61fac01d7e3e52871b941f580dff76",
    "_ttp": "2ff3Ir0MxKX704xZuqiM6s0eJIO",
    "tt_csrf_token": "AE2hXMUQ-6rhGwbh7wNuUIzb_lClg_9djP00",
    "ttwid": "1%7CNDCsIYIXqn6SeA1ag50iRZ3_CWvTAyJaKGHMWPgCQ6U%7C1716590063%7C80e796e0aa9c212b1c316f674daf9a834136a1d8905562a2975dec28e99eca9b",
    "ak_bmsc": "D6A3FBA4C2CC8C805D198A99C8CD107B~000000000000000000000000000000~YAAQz9fdF0vhCVKPAQAAorG9rBcffdiiqiJ0VRcBvYc+wLjKVbpe7fyG7o2LySWDKbCGlue8orBmzPWx5kflbS3oZy7X05ngYEdw/waImS1V0pz57zcqhOI87RZeLYPykpmMUi0gxFfPAPcF3fOjbtDzSRy7aRuGLkjbMUo0etpgcupD/nSOrgvIlFTj4GivHgnp+3jP306WUfIPJZJXo7mqEUnnSpbYonaHr0DskOPxNP83xpDxmjkmLm9MO8Svi+4g1hJG1xFI5DAcUpzAtiaYFscx13iDUElq24m30Xup+r4sV6rtcyqoagyT0PAraPu8qUW9AkmelcrmJHIpe2DDwaOl6VYD9ccFFA2ALhHjeQr5vL9y/UoKYCEP6IvnMRZRpD1mf7PrlQ==",
    "tt_chain_token": "xqy2ATAEzfrk23JRxiruIA==",
    "bm_sv": "101CC29D3B945A860A9F49F9F3FB604F~YAAQ2tfdF/2p+qOPAQAAq3/LrBdT6rRF/jLeCyGf8LdgPdQgVCPHOwSPR4Zi5clJROCzbmTltLsDsbStu+izgJQQal5XCjtk/U8S/OTFOCuEFKcLHbyyXDZIOYdYyl199KCIRxh2nxXS/NPt6aIDCJGA8cAxaotcByiKr5Jvb7JgBVFamgydfF7lMYHrD/InpJBZR45igGJ1IkHjm15jDOX1NorS+OdmppyqQSo3Z6mibbENk85GnkXySAdZFDA7~1",
    "msToken": "7i1l8Sk-tu4fw8Wg1biL4XvJPamFduDorEAUoC5R1imd5U5XFnzosigxTQQlyLP6QrfbctvkW6wgIh-wudjnshrjHiN5uO1Ky-HDaKWY8jbZsX9kNC-wF0T-nkraVMBqByGD0rK7gP-r"
}

response = requests.get(url=url, cookies=cookies)

DownloadBar().download(dest='video.mp4', title='Video', response=response)

 ```
 now the actual video is downloaded
output_response

Now thinking about it the package is named simple for a reason so maybe it isn't wise to include the extra parameter and having to deal with error handling.

**Comment by mimseyedi** [comment]
First of all, thank you for your time and explanation. Although this
project is a simple project and I just wanted to make a download bar under
the terminal for myself to enjoy and be comfortable with, I have no problem
with developing it. I was even thinking that, for example, if needed,
cookies can be considered as an independent parameter and added to the
Response object in the body of the download method. In any case, if you
have a desire to develop the project, I welcome it and we can think of ways
to do it. I hope Luck.

**Comment by geovanigaldemsugar** [comment]
Alright man, appreciate the response. When i have some free time i definitely will.

**Pull request closed without merging**
